### ISSUE TITLE
Bug in small-sample correction

### ISSUE THREAD

**Issue by jepusto** [zackfisher/robumeta#7] opened 2017-02-21 14:55 UTC
@windshield999 @zackfisher Commit 7e76317 introduces an error (and inefficiencies) into the small-sample correction formula. See my comments on the commit.

**Comment by zackfisher** [comment] 2017-02-22 20:15
@jepusto @windshield999 ,

Did the changes made in 51c4ca7030e546920ebbb4d8112c89410d8353f6 address these concerns? I'd like to push Version 1.9 to Cran but wanted to see if we could close this issue first. 

Zack

**Comment by windshield999** [comment] 2017-02-22 20:22
Dear Zack!

Hi! 

Could you please give me one day time to check the code?

I was wrong. The original formulas are all correct. The problem is actually caused by singularity.  We need to implement the implement the Moore-Penrose pseudo inverse to prevent that. I have finished the coding, but I want to test it first. 

Thank you very much,
Zhipeng

**Closed as completed** 2017-05-26 23:49 UTC
